// <auto-generated />
namespace ProjectExpenseControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Store_Procedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Store_Procedures));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210445073_Store_Procedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
