//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectExpenseControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectExpenseControl.ResourceSQL", typeof(ResourceSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	/*
        ///	Este store sirve para ingresar un usuario y proporcionarle el permiso por
        ///	defecto de Usuario
        ///	*/
        ///USE DBProgramExpenses
        ///if exists (select * from dbo.sysobjects where id = object_id(&apos;SP_DeleteUserRemoveRole&apos;) and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///drop procedure [dbo].SP_DeleteUserRemoveRole
        ///GO
        ///	CREATE PROCEDURE SP_DeleteUserRemoveRole	
        ///			@USR_IDE_USER int
        ///	AS
        ///	BEGIN
        ///		DECLARE @ErrorMessage varchar(max)
        ///
        ///	BEGIN TRY		
        ///		BEGIN TRAN
        ///			DELETE FROM Users WHERE USR_IDE_USER = @USR_IDE_U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SP_DeleteUserRemoveRole {
            get {
                return ResourceManager.GetString("Create_SP_DeleteUserRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	/*
        ///	Este store sirve para ingresar un usuario y proporcionarle el permiso por
        ///	defecto de Usuario
        ///	*/
        ///USE DBProgramExpenses
        ///if exists (select * from dbo.sysobjects where id = object_id(&apos;SP_InsertUserAddRoleDefault&apos;) and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///drop procedure [dbo].SP_InsertUserAddRoleDefault
        ///GO
        ///	CREATE PROCEDURE SP_InsertUserAddRoleDefault	
        ///			@USR_IDE_AREA nvarchar(100),
        ///			@USR_DES_POSITION nvarchar(60),
        ///			@USR_DES_NAME nvarchar(100),
        ///			@USR_DES_FIRST_NAME nvarchar(60),
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_SP_InsertUserAddRoleDefault {
            get {
                return ResourceManager.GetString("Create_SP_InsertUserAddRoleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DROP PROCEDURE DBProgramExpenses.dbo.SP_InsertUserAddRoleDefault
        /// DROP PROCEDURE DBProgramExpenses.dbo.SP_DeleteUserRemoveRole.
        /// </summary>
        internal static string DROP_SP {
            get {
                return ResourceManager.GetString("DROP_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DBO].[SP_DeleteUserRemoveRole] @USR_IDE_USER.
        /// </summary>
        internal static string SP_DeleteUserRemoveRole {
            get {
                return ResourceManager.GetString("SP_DeleteUserRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [dbo].[SP_InsertUserAddRoleDefault] @USR_IDE_AREA, @USR_DES_POSITION, @USR_DES_NAME, @USR_DES_FIRST_NAME, @USR_DES_LAST_NAME,    @USR_DES_PASSWORD, @USR_DES_PHONE,  @USR_DES_EMAIL,  @USR_FH_CREATED.
        /// </summary>
        internal static string SP_InsertUserAddRoleDefault {
            get {
                return ResourceManager.GetString("SP_InsertUserAddRoleDefault", resourceCulture);
            }
        }
    }
}
